### ISSUE TITLE
v1.4.2 patch release checklist

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/q#769]
- [ ] add style check back to travis CI
- [ ] style audit (e.g., remove superfluous parens)
- [ ] verify that all error messages take the form "Q can't" instead of "Can't"
- [ ] verify that all missing-callback cases are treated consistently (throw helpful error message, check for typeof function (not merely undefined, not specifically callback.apply)
- [ ] add "and Contributors" to copyright byline

On a side note, it’s beyond time to move to eslint and start locking style down more.
